import React from "react";

type PolicyPurposeType = {
  header: string;
  description: string;
};

const policyPurpose: PolicyPurposeType[] = [
  {
    header: "Account",
    description:
      "refers to a unique account created for you to access our services or parts of our services.",
  },
  {
    header: "Company",
    description:
      "(referred to as either “the Company”, “We”, “Us”, or “Our”) refers to We Are Globex, a company registered in the United Kingdom.",
  },
  {
    header: "Cookies",
    description:
      "are small files placed on your device (computer, mobile, or tablet) by a website to collect browsing data.",
  },
  {
    header: "Device",
    description:
      "refers to any device capable of accessing our service, such as a computer, smartphone, or tablet.",
  },
  {
    header: "Personal Data",
    description: "means any information that can identify an individual.",
  },
  {
    header: "Service",
    description:
      "refers to the website and related services provided by We Are Globex.",
  },
  {
    header: "Service Provider",
    description:
      "refers to third-party companies or individuals employed by the Company to facilitate or provide services on its behalf.",
  },
  {
    header: "Usage Data",
    description:
      "refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (e.g., the duration of a page visit).",
  },
  {
    header: "Website",
    description:
      "refers to the online platform operated by We Are Globex, accessible at https://weareglobex.com/.",
  },
  {
    header: "You",
    description:
      "refers to the individual accessing or using our services, or the legal entity on whose behalf the individual is accessing or using the services.",
  },
];

const personalData = [
  "Email",
  "First and last name",
  "Phone number",
  "Address, including city, state, postal code, and country",
  "Usage Data",
];

const usagesData = [
  "Your device’s Internet Protocol (IP) address",
  "Browser type and version",
  "Pages you visit on our website",
  "The time and date of your visit",
  "Time spent on those pages",
  "Device identifiers and diagnostic data",
];

const managementPersonalData = [
  {
    header: "To provide and maintain our services:",
    description: "This includes monitoring the usage of our services.",
  },
  {
    header: "To manage your account:",
    description:
      "Your personal data helps us manage your registration and access to the service.",
  },
  {
    header: "For contract performance:",
    description:
      "To fulfill contracts, such as delivering services or processing transactions you have requested.",
  },
  {
    header: "To contact you:",
    description:
      "We may contact you via email, phone, SMS, or other communication channels for updates or notifications.",
  },
  {
    header: "To send promotional materials:",
    description:
      "If you have opted in, we may send you promotional offers, updates, and general information about similar services or products.",
  },
  {
    header: "To process requests:",
    description:
      "We use your data to address your queries and provide support.",
  },
  {
    header: "For business transfers:",
    description:
      "Your data may be transferred as part of a business transaction, such as a merger or acquisition.",
  },
];

const circumstances = [
  {
    header: "For legal purposes:",
    description:
      "If required by law, we may disclose your data to authorities.",
  },
  {
    header: "For business transactions:",
    description:
      "In the event of a merger, acquisition, or sale of assets, your data may be transferred.",
  },
  {
    header: "To protect our rights:",
    description:
      "We may disclose your data to protect the Company’s rights or property.",
  },
];

const Policies = () => {
  return (
    <section className="py-16 bg-gray-50">
      <div className="container mx-auto px-6 lg:px-12">
        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Last updated: September 25, 2024
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          This Privacy Policy outlines our policies and practices on the
          collection, use, and disclosure of your information when you use our
          services. It also informs you of your privacy rights and how the law
          protects you.
        </p>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          We use your personal data to provide and improve our services. By
          using the service, you agree to the collection and use of your
          information in accordance with this Privacy Policy.
        </p>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Interpretation and Definitions
        </h3>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Interpretation
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          Words with capitalized initial letters have specific meanings defined
          below. These definitions apply whether the terms are used in singular
          or plural form.
        </p>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Definitions
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          For the purposes of this Privacy Policy: -{" "}
        </p>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          {policyPurpose.map((policy) => (
            <div key={policy.header} className="space-y-2">
              • <strong>{policy.header}</strong> {policy.description}
            </div>
          ))}
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Collecting and Using Your Personal Data
        </h3>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Types of Data Collected
        </h3>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Personal Data
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          While using our services, we may ask you to provide certain personally
          identifiable information, such as:
        </p>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          {personalData.map((data, index) => (
            <div key={index} className="space-y-2">
              • {data}
            </div>
          ))}
        </p>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Usage Data
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          Usage Data is collected automatically during your interactions with
          the service. This may include:
        </p>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          {usagesData.map((data, index) => (
            <div key={index} className="space-y-2">
              • {data}
            </div>
          ))}
        </p>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          When accessing the service via a mobile device, we may collect
          additional information such as your mobile device type, operating
          system, IP address, and unique identifiers.
        </p>

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900">
          Tracking Technologies and Cookies
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          When you visit or log in to our website, cookies and similar
          technologies may be used by our online data partners or vendors to
          associate these activities with other personal information they or
          others have about you, including by association with your email. We
          (or service providers on our behalf) may then send communications and
          marketing to these email. You may opt out of receiving this
          advertising by visiting https://app.retention.com/optout
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Use of Your Personal Data
        </h3>

        <h2 className="text-lg font-bold mb-4 leading-tight text-gray-900">
          Globex Management may use your personal data for the following
          purposes:
        </h2>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          {managementPersonalData.map((policy) => (
            <div key={policy.header} className="space-y-2">
              • <strong>{policy.header}</strong> {policy.description}
            </div>
          ))}
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Retention of Your Personal Data
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          We will retain your personal data only as long as necessary to fulfill
          the purposes outlined in this Privacy Policy. Usage Data will be
          retained for a shorter period unless needed for security purposes or
          legal compliance.
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Transfer of Your Personal Data
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          Your information may be transferred to computers located outside your
          state or country where data protection laws may differ from those in
          your jurisdiction. By submitting your personal data, you agree to this
          transfer. We will ensure that your data is treated securely and that
          appropriate safeguards are in place.
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Your Data Protection Rights
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          You have the right to access, correct, or delete the personal data we
          hold about you. You may update or delete your data via your account
          settings or by contacting us directly. However, we may retain certain
          data when required by law.
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Disclosure of Your Personal Data
        </h3>

        <h2 className="text-lg font-bold mb-4 leading-tight text-gray-900">
          We may disclose your personal data under the following circumstances:
        </h2>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          {circumstances.map((data) => (
            <div key={data.header} className="space-y-2">
              • <strong>{data.header}</strong> {data.description}
            </div>
          ))}
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Security of Your Personal Data
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          We take the security of your personal data seriously, but no method of
          transmission over the Internet or electronic storage is completely
          secure. We strive to use commercially acceptable means to protect your
          data, but we cannot guarantee absolute security.
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Children’s Privacy
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          Our services do not address anyone under the age of 13, and we do not
          knowingly collect personal data from children under 13.
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Changes to This Privacy Policy
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          We may update this Privacy Policy from time to time. Any changes will
          be posted on this page, with an updated “Last updated” date. We
          encourage you to review this Privacy Policy periodically for any
          updates.
        </p>

        <hr />

        <h3 className="text-xl font-bold mb-4 leading-tight text-gray-900 mt-5">
          Contact Us
        </h3>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          If you have any questions about this Privacy Policy, please contact
          us:
        </p>

        <p className="text-lg font-bold mb-4 leading-tight text-gray-900">
          <div className="space-y-2">
            • <strong>By email:</strong> info@weareglobex.com
          </div>
        </p>
      </div>
    </section>
  );
};

export default Policies;
