"use client";

import { sans, serif } from "@/lib/utils";
import { useState, useEffect } from "react";

const sections = [
  {
    id: "interpretation",
    title: "Interpretation and Definitions",
    content: [
      {
        heading: "Interpretation",
        body: "Words with capitalised initial letters have specific meanings defined below. These definitions apply whether the terms are used in singular or plural form.",
      },
      {
        heading: "Definitions",
        body: "For the purposes of this Privacy Policy:",
        list: [
          "<strong>Account</strong> refers to a unique account created for you to access our services or parts of our services.",
          '<strong>Company</strong> (referred to as either "the Company", "We", "Us", or "Our") refers to We Are Globex, a company registered in the United Kingdom.',
          "<strong>Cookies</strong> are small files placed on your device (computer, mobile, or tablet) by a website to collect browsing data.",
          "<strong>Device</strong> refers to any device that can access the service, such as a computer, mobile phone, or digital tablet.",
          "<strong>Personal Data</strong> means any information that can identify an individual.",
          "<strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company. This refers to third-party companies or individuals engaged by the Company to facilitate or provide services on its behalf.",
          "<strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (e.g., duration of a page visit).",
          "<strong>Website</strong> refers to the online platform operated by We Are Globex, accessible at https://weareglobex.com.",
          "<strong>You</strong> refers to the individual accessing or using the services, or the legal entity on whose behalf the individual is accessing or using the services.",
        ],
      },
    ],
  },
  {
    id: "data-collected",
    title: "Types of Data Collected",
    content: [
      {
        heading: "Personal Data",
        body: "While using our services, we may ask you to provide certain personally identifiable information, such as:",
        list: [
          "Email address",
          "First and last name",
          "Phone number",
          "Address, including city, state, postal code, and country",
          "Usage data",
        ],
      },
      {
        heading: "Usage Data",
        body: "Usage data is collected automatically during your interactions with the service. This may include:",
        list: [
          "Your device's Internet Protocol (IP) address",
          "Browser type and version",
          "Pages you visit on our site",
          "The time and date of your visit",
          "Time spent on those pages",
          "Device identifiers and diagnostic data",
          "When accessing the service via a mobile device, we may collect additional information such as your mobile device type, operating system, IP address, and unique identifiers.",
        ],
      },
    ],
  },
  {
    id: "tracking",
    title: "Tracking Technologies and Cookies",
    content: [
      {
        body: "We use cookies, web beacons, pixels, and similar technologies to track activity on our online data platforms or vendors to associate these activities with other personal information they or others have about you, including by association with your emails. We (or service providers on our behalf) may then send communications and advertising via these emails. You may opt out of receiving this advertising by visiting https://app.retention.com/optout.",
      },
    ],
  },
  {
    id: "use-of-data",
    title: "Use of Your Personal Data",
    content: [
      {
        body: "Sticker Management may use your personal data for the following purposes:",
        list: [
          "<strong>To provide and maintain our services:</strong> This includes monitoring the usage of our services.",
          "<strong>To manage your account:</strong> Your personal data helps us manage your registration and access to the service.",
          "<strong>To fulfil a contract:</strong> This includes the development and delivery of goods or services you have requested.",
          "<strong>To contact you:</strong> We may contact you via email, phone, SMS, or other communication channels for updates or notifications.",
          "<strong>To send promotional communications:</strong> If you have opted in, we may send you promotional offers, updates, and general information about similar services or products.",
          "<strong>To process requests:</strong> We use your data to address your queries and provide support.",
          "<strong>For business transactions:</strong> Your data may be transferred as part of a business transaction, such as a merger or acquisition.",
        ],
      },
    ],
  },
  {
    id: "retention",
    title: "Retention of Your Personal Data",
    content: [
      {
        body: "We will retain your personal data only as long as necessary to fulfil the purposes outlined in this Privacy Policy. Usage data will be retained for a shorter period, unless needed for security reasons or legal compliance.",
      },
    ],
  },
  {
    id: "transfer",
    title: "Transfer of Your Personal Data",
    content: [
      {
        body: "Your information may be transferred to computers located outside your state or country where data protection laws may differ from those in your jurisdiction. By submitting your personal data, you agree to this transfer. We will ensure that your data is treated securely and that appropriate safeguards are in place.",
      },
    ],
  },
  {
    id: "rights",
    title: "Your Data Protection Rights",
    content: [
      {
        body: "You have the right to access, update, or delete the personal data we hold about you. You may update or delete your data via your account settings or by contacting us directly. However, we may retain certain data when required by law.",
      },
    ],
  },
  {
    id: "disclosure",
    title: "Disclosure of Your Personal Data",
    content: [
      {
        body: "We may disclose your personal data under the following circumstances:",
        list: [
          "<strong>For legal purposes:</strong> If required by law, we may disclose your information to authorities.",
          "<strong>For business transactions:</strong> In the event of a merger, acquisition, or sale of assets, your data may be transferred.",
          "<strong>To protect our rights:</strong> We may disclose data to protect the Company's rights or property.",
        ],
      },
    ],
  },
  {
    id: "security",
    title: "Security of Your Personal Data",
    content: [
      {
        body: "We take the security of your personal data seriously, but no method of transmission over the internet or electronic storage is completely secure. We strive to use commercially acceptable means to protect your data, but we cannot guarantee absolute security.",
      },
    ],
  },
  {
    id: "children",
    title: "Children's Privacy",
    content: [
      {
        body: "Our services do not address anyone under the age of 13, and we do not knowingly collect personal data from children under 13.",
      },
    ],
  },
  {
    id: "changes",
    title: "Changes to This Privacy Policy",
    content: [
      {
        body: 'We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated "Last updated" date. We encourage you to review this Privacy Policy periodically for any updates.',
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Us",
    content: [
      {
        body: "If you have any questions about this Privacy Policy, please contact us:",
        list: ["<strong>By email:</strong> info@weareglobex.com"],
      },
    ],
  },
];

export function Body() {
  const [activeSection, setActiveSection] = useState(sections[0].id);

  useEffect(() => {
    const h = () => {
      let current = sections[0].id;
      for (const s of sections) {
        const el = document.getElementById(`pp-${s.id}`);
        if (el && el.getBoundingClientRect().top <= 120) {
          current = s.id;
        }
      }
      setActiveSection(current);
    };
    h();
    window.addEventListener("scroll", h, { passive: true });
    window.addEventListener("resize", h);
    return () => {
      window.removeEventListener("scroll", h);
      window.removeEventListener("resize", h);
    };
  }, []);
  return (
    <div className="max-w-7xl mx-auto px-6 py-16">
      <div className="grid grid-cols-1 lg:grid-cols-[260px_1fr] gap-16">
        {/* Sticky sidebar nav */}
        <aside className="hidden lg:block">
          <div className="sticky top-24">
            <p
              className="text-[0.6rem] uppercase tracking-widest text-[#3a3f4d] mb-5"
              style={sans(500)}
            >
              Contents
            </p>
            <nav className="space-y-1">
              {sections.map((s) => (
                <a
                  key={s.id}
                  href={`#pp-${s.id}`}
                  className="block py-2 px-3 text-xs transition-colors border-l-2"
                  style={{
                    ...sans(activeSection === s.id ? 500 : 400),
                    color: activeSection === s.id ? "#e8a020" : "#7a7f8e",
                    borderLeftColor:
                      activeSection === s.id ? "#e8a020" : "transparent",
                  }}
                >
                  {s.title}
                </a>
              ))}
            </nav>
          </div>
        </aside>

        {/* Policy content */}
        <main className="min-w-0">
          {/* Intro */}
          <div className="pb-12 mb-12 border-b border-border">
            <p
              className="text-sm text-secondary-foreground leading-relaxed"
              style={sans()}
            >
              We use your personal data to provide and improve our services. By
              using the service, you agree to the collection and use of
              information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-0">
            {sections.map((section, idx) => (
              <section
                key={section.id}
                id={`pp-${section.id}`}
                className="pb-12 mb-12 border-b border-border last:border-0 last:mb-0 scroll-mt-24"
              >
                <div className="flex items-start gap-4 mb-6">
                  <span
                    className="text-[0.65rem] text-[#3a3f4d] mt-1.5 tabular-nums"
                    style={sans(500)}
                  >
                    {String(idx + 1).padStart(2, "0")}
                  </span>
                  <h2
                    className="text-2xl md:text-3xl uppercase leading-tight"
                    style={serif()}
                  >
                    {section.title}
                  </h2>
                </div>

                <div className="space-y-6 pl-8">
                  {section.content.map((block, bi) => (
                    <div key={bi}>
                      {'heading' in block && block.heading && (
                        <h3
                          className="text-xs uppercase tracking-widest text-[#e8a020] mb-3"
                          style={sans(500)}
                        >
                          {block.heading}
                        </h3>
                      )}
                      {block.body && (
                        <p
                          className="text-sm text-secondary-foreground leading-relaxed mb-4"
                          style={sans()}
                        >
                          {block.body}
                        </p>
                      )}
                        {'list' in block && block.list && (
                        <ul className="space-y-2.5">
                          {block.list.map((item, li) => (
                            <li key={li} className="flex gap-3">
                              <span className="text-[#e8a020] text-xs mt-1 shrink-0">
                                →
                              </span>
                              <span
                                className="text-sm text-secondary-foreground leading-relaxed"
                                style={sans()}
                                dangerouslySetInnerHTML={{ __html: item }}
                              />
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}
